function [fitresult, gof] = createFit(X, Y, Mt_Bruno)
%CREATEFIT(X,Y,MT_BRUNO)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: X
%      Y Input: Y
%      Z Output: Mt_Bruno
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Nov-2023 15:19:33


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( X, Y, Mt_Bruno );

% Set up fittype and options.
ft = 'cubicinterp';
opts = fitoptions( 'Method', 'CubicSplineInterpolant' );
opts.ExtrapolationMethod = 'none';
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.


